server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sz   # 所有Entity别名类所在包
  mapper-locations:
  - classpath:com/sz/dao/*.xml                       # mapper映射文件
    
spring:
   application:
    name: microservicecloud-dept    #对外暴露的微服务名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driverClassName: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/spring1              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
eureka:
  client: #服务提供方注册进eureka服务列表内，属于eureka的客户端
    service-url:     #Eureka的地址
#      defaultZone: http://localhost:7001/eureka/   单个服务注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群环境



info:
  app.name: microservicecloud-dept
  company.name: com.sz
  build.artifactId: $project.artifactId$
  build.version: $project.version$